"""Structural types for the RESP-protocol client shared by Redis and Valkey.

Both backends speak the same protocol, so the subset the queue relies on is
described once here. These are pure ``typing`` protocols: importing this
module never imports a client package.
"""

import builtins
from typing import Any, Protocol


class PipelineLike(Protocol):
    """Pipeline subset used by the Redis and Valkey queue backends."""

    def delete(self, *keys: str) -> object: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: str) -> object: ...

    def hgetall(self, key: str) -> object: ...

    def hset(
        self, name: str, key: str | None = None, value: Any | None = None, *, mapping: dict[str, str] | None = None
    ) -> object: ...

    def scard(self, key: str) -> object: ...

    def sadd(self, key: str, *values: str) -> object: ...

    def smembers(self, key: str) -> object: ...

    def zadd(self, name: str, mapping: dict[str, float]) -> object: ...

    def zrem(self, name: str, *values: str) -> object: ...

    def execute(self) -> object: ...


class PubSubLike(Protocol):
    """PubSub subset used by the Redis and Valkey queue backends."""

    def subscribe(self, channel: str) -> object: ...

    async def get_message(self, *, ignore_subscribe_messages: bool, timeout: float | None) -> Any: ...

    def unsubscribe(self, channel: str) -> object: ...


class ClientLike(Protocol):
    """Async RESP-protocol client subset used by the queue backends."""

    def pubsub(self) -> PubSubLike: ...

    def pipeline(self, *, transaction: bool = False) -> PipelineLike: ...

    async def delete(self, *keys: str) -> Any: ...

    def eval(self, script: str, numkeys: int, *keys_and_args: str) -> Any: ...

    async def hget(self, name: str, key: str) -> Any: ...

    async def hdel(self, name: str, *keys: str) -> Any: ...

    async def hgetall(self, name: str) -> dict[Any, Any]: ...

    async def hset(
        self, name: str, key: str | None = None, value: Any | None = None, *, mapping: dict[str, str] | None = None
    ) -> Any: ...

    async def publish(self, channel: str, message: str) -> Any: ...

    def set(self, name: str, value: str, *, nx: bool = False, px: int | None = None) -> Any: ...

    async def smembers(self, key: str) -> builtins.set[Any]: ...

    async def zadd(self, name: str, mapping: dict[str, float]) -> Any: ...

    async def zrange(self, name: str, start: int, end: int) -> list[Any]: ...

    async def zrangebyscore(
        self, name: str, minimum: float | str, maximum: float | str, *, start: int | None = None, num: int | None = None
    ) -> list[Any]: ...

    async def zrem(self, name: str, *values: str) -> Any: ...
